export const PARKS_MAP: Record<string, string> = {
  "B001": "American Playground",
  "B002": "Amersfort Park",
  "B003": "Bartel-Pritchard Square",
  "B006": "Beattie Square",
  "B007": "Bensonhurst Park",
  "B008": "Betsy Head Park",
  "B010": "Brooklyn Botanic Garden",
  "B012": "Brower Park",
  "B016": "Maria Hernandez Park",
  "B017": "Bushwick Playground",
  "B018": "Canarsie Park",
  "B019": "Carroll Park",
  "B021": "Commodore Barry Park",
  "B022": "Sarah J.S. Tompkins Garnet Playground",
  "B023": "Lafayette Playground",
  "B025": "Cooper Park",
  "B026": "Cuyler Gore Park",
  "B027": "Veterans Triangle",
  "B028": "Dyker Beach Park",
  "B029": "Eastern Parkway",
  "B030": "Eastern Parkway Extension",
  "B031": "Fidelity Triangle",
  "B032": "Fort Greene Park",
  "B033": "Fort Hamilton Triangle",
  "B035": "John Paul Jones Park",
  "B036": "Fort Stirling Park",
  "B037": "Freedom Triangle",
  "B038": "Fulton Park",
  "B040": "Grand Army Plaza",
  "B041": "Grant Gore",
  "B042": "Gravesend Park",
  "B043": "Greenpoint Playground",
  "B044": "Dr. Ronald McNair Park",
  "B045": "Heisser Triangle",
  "B047": "Highland Park",
  "B048": "Brooklyn Museum",
  "B049": "Irving Square Park",
  "B050": "Van Voorhees Playground",
  "B051": "Kelly Park Playground",
  "B052": "Leif Ericson Park",
  "B054": "Lincoln Terrace / Arthur S. Somers Park",
  "B055": "Sternberg Park",
  "B056": "Martin Luther King Jr. Playground",
  "B057": "Marine Park",
  "B058": "McCarren Park",
  "B060": "McKinley Park",
  "B061": "McLaughlin Park",
  "B062": "Memorial Gore",
  "B063": "Milestone Park",
  "B065": "Ocean Parkway Malls",
  "B066": "Owl's Head Park",
  "B068": "Parade Ground",
  "B070": "Machate Circle",
  "B073": "Prospect Park",
  "B077": "Coffey Park",
  "B078": "Grace Playground",
  "B079": "Saratoga Park",
  "B080": "Asser Levy Park",
  "B082": "Shore Park and Parkway",
  "B085": "Metropolitan Recreation Center",
  "B087": "Sunset Park",
  "B088": "Herbert Von King Park",
  "B089": "Lowry Triangle",
  "B090": "Sobel Playground",
  "B093": "Weeksville Playground",
  "B094": "Sgt. Joyce Kilmer Square",
  "B095": "Ennis Playground",
  "B096": "Sgt. William Dougherty Playground",
  "B097": "Sledge Playground",
  "B098": "Martin Luther Playground",
  "B099": "Lt. Joseph Petrosino Park",
  "B100": "Seth Low Playground/ Bealin Square",
  "B102": "Crispus Attucks Playground",
  "B103": "Cypress Hills Playground",
  "B105": "Taaffe Playground",
  "B107": "Lion's Pride Playground",
  "B109": "Bill Brown Playground",
  "B110": "Marion Hopkinson Playground",
  "B111": "Washington Park",
  "B114": "Msgr. McGolrick Park",
  "B115": "Cohn Triangle",
  "B116": "Zion Triangle",
  "B117": "Lindsay Triangle",
  "B121": "Dodger Playground",
  "B123": "Alben Square",
  "B124": "William Sheridan Playground",
  "B125": "Calvert Vaux Park",
  "B126": "Red Hook Recreation Area",
  "B127": "Martinez Playground",
  "B128": "Colonel David Marcus Playground",
  "B129": "Kaiser Park",
  "B130": "Greenwood Playground",
  "B131": "Rudd Playground",
  "B132": "Gilbert Ramirez Park",
  "B135": "Newtown Barge Playground",
  "B137": "Sixteen Sycamores Playground",
  "B139": "Heckscher Playground",
  "B140": "Banneker Playground",
  "B141": "City Line Park",
  "B142": "Bedford Playground",
  "B144": "Ocean Hill Playground",
  "B145": "Thomas Greene Playground",
  "B146": "Quaker Parrot Park at the Dust Bowl",
  "B147": "Monsignor Crawford Field",
  "B148": "Rolph Henry Playground",
  "B150": "Kolbert Playground",
  "B151": "Dome Playground",
  "B152": "Rappaport Playground",
  "B153": "South Pacific Playground",
  "B154": "Berry Playground",
  "B155": "Triangle",
  "B156": "Powell Playground",
  "B158": "Garibaldi Playground",
  "B159": "Mount Prospect Park",
  "B160": "Ketchum Triangle",
  "B161": "James Forten Playground",
  "B162": "Brizzi Playground",
  "B163": "Sperandeo Brothers Playground",
  "B164": "Bath Beach Park",
  "B165": "Spring Creek Park",
  "B166": "Belt Parkway/Shore Parkway",
  "B167": "La Guardia Playground",
  "B168": "Continental Army Plaza",
  "B169": "Coney Island Beach & Boardwalk",
  "B171": "Linden Sitting Area",
  "B172": "Heffernan Triangle",
  "B173": "Fraser Square",
  "B174": "Park",
  "B175": "Dahill Triangle",
  "B176": "Trust Triangle",
  "B178": "Flatbush Malls",
  "B180": "Flatbush Mall",
  "B182": "Howard Malls",
  "B184": "Avenue R Mall",
  "B190": "Barone Triangle",
  "B192": "Russell Pedersen Playground",
  "B193": "Hamilton Metz Field",
  "B194": "Harmony Triangle",
  "B196": "Pvt. Sonsire Triangle",
  "B197": "Mellett Playground",
  "B198": "Kings Highway Malls",
  "B200": "Elizabeth Stroud Playground",
  "B202": "Lithuania Square",
  "B205": "Corporal Wiltshire Square",
  "B206": "Sunners Playground",
  "B207": "Sarsfield Playground",
  "B208": "Pfc Norton Playground",
  "B209": "Galapo Playground",
  "B211": "Lady Moody Triangle",
  "B212": "Hot Spot Tot Lot",
  "B213": "Gravesend Triangle",
  "B214": "Linden Park",
  "B215": "Decatur Playground",
  "B216": "Raymond Bush Playground",
  "B217": "Marcy Playground",
  "B218": "Paerdegat Park",
  "B219": "Callahan-Kelly Playground",
  "B220": "Washington Hall Park",
  "B221": "Steuben Playground",
  "B222": "Pierrepont Playground",
  "B224": "P.O. Reinaldo Salgado Playground",
  "B225": "St. Andrew's Playground",
  "B226": "Mt. Carmel Triangle",
  "B227": "P.S. 125 Playground",
  "B228": "Dr. Green Playground",
  "B230": "Nicholas Naquan Heyward Jr. Park",
  "B231": "Samuel Goldberg Triangle",
  "B232": "Dean Playground",
  "B234": "Tilden Playground",
  "B235": "Herman Dolgon Playground",
  "B236": "Glenwood Playground",
  "B237": "John Hancock Playground",
  "B239": "Sheepshead Playground",
  "B240": "Tucker Place",
  "B242": "Meucci Triangle",
  "B243": "Golconda Playground",
  "B244": "McDonald Playground",
  "B245": "St. John's Park",
  "B246": "Jerome Playground",
  "B247": "Breukelen Ballfields",
  "B248": "Fox Playground",
  "B249": "Van Dyke Playground",
  "B250": "Nostrand Playground",
  "B251": "Manhattan Beach Park",
  "B252": "West Playground",
  "B253": "Albert L. Parham Playground",
  "B254": "Wingate Park",
  "B256": "Brooklyn Academy Of Music",
  "B257": "Frost Playground",
  "B258": "Brevoort Playground",
  "B259": "Underwood Park",
  "B260": "Howard Playground",
  "B261": "Sankofa Park",
  "B262": "Potomac Playground",
  "B263": "Sumner Playground",
  "B264": "Roebling Playground",
  "B265": "Rainbow Playground",
  "B266": "Star Spangled Playground",
  "B267": "Winthrop Playground",
  "B268": "Nautilus Playground",
  "B269": "Jesse Owens Playground",
  "B270": "Brownsville Playground",
  "B271": "Railroad Playground",
  "B272": "Marlboro Playground",
  "B273": "Aimee Triangle",
  "B274": "Bayview Playground",
  "B275": "Grady Playground",
  "B276": "Person Square",
  "B277": "Benson Playground",
  "B278": "Sam Leggio Triangle",
  "B279": "Wilson Playground",
  "B280": "Nellie Bly Park",
  "B282": "Patrick O'Rourke Playground",
  "B283": "Belmont Playground",
  "B284": "Marc And Jason's Playground",
  "B285": "Harry Maze Playground",
  "B286": "Bartlett Playground",
  "B287": "Andries Playground",
  "B288": "Slope Park Playground",
  "B289": "Cutinella Triangle",
  "B290": "Public Place",
  "B291": "Power Playground",
  "B292": "Pratt Playground",
  "B293": "Classon Playground",
  "B294": "Jackie Robinson Park Playground",
  "B295": "Oxport Playground",
  "B296": "Luna Playground",
  "B297": "Albemarle Playground",
  "B298": "Stockton Playground",
  "B300": "Oracle Playground",
  "B301": "Greene Playground",
  "B302": "Charlie's Place",
  "B304": "Kennedy King Playground",
  "B305": "P.S. 279 Playground",
  "B306": "Playground 286",
  "B307": "Tiger Playground",
  "B308": "Yak Playground",
  "B309": "Pink Playground",
  "B311": "Ten Eyck Playground",
  "B312": "Woodruff Playground",
  "B313": "El Shabazz Playground",
  "B315": "Surf Playground",
  "B316": "DiGilio Playground",
  "B317": "Lafayette Gardens Playground",
  "B320": "Park Slope Playground",
  "B321": "Edmonds Playground",
  "B322": "Pulaski Playground",
  "B323": "Hattie Carthan Playground",
  "B324": "Jacob Joffe Fields",
  "B325": "Fish Playground",
  "B326": "Cobble Hill Park",
  "B329": "Lindower Park",
  "B330": "Hickman Playground",
  "B331": "Neptune Playground",
  "B332": "Evergreen Playground",
  "B334": "Fermi Playground",
  "B335": "Bildersee Playground",
  "B336": "Abe Stark Skating Rink",
  "B337": "Century Playground",
  "B338": "Tom McDonald Triangle",
  "B339": "Newport Playground",
  "B340": "Garden Playground",
  "B342": "100% Playground",
  "B343": "Osborn Playground",
  "B345": "Ethan Allen Playground",
  "B346": "Ericsson Playground",
  "B347": "Carver Playground",
  "B348": "Willoughby Playground",
  "B349": "Bath Playground",
  "B350": "Stroud Playground",
  "B351": "Kosciuszko Pool",
  "B352": "Curtis Playground",
  "B353": "Bergen Beach Playground",
  "B356": "North Pacific Playground",
  "B357": "Jackie Robinson Playground",
  "B358": "De Hostos Playground",
  "B359": "Eleanor Roosevelt Playground",
  "B360": "Remsen Playground",
  "B361": "Boerum Park",
  "B362": "Chester Playground",
  "B363": "Houston Playground",
  "B364": "Woods Playground",
  "B366": "Duke Park",
  "B367": "Livonia Park",
  "B368": "The Cyclone",
  "B369": "Steeplechase Park",
  "B372": "Friends Field",
  "B375": "Chiarantano Playground",
  "B376": "Fidler-Wyckoff House Park",
  "B377": "Floyd Patterson Ballfields",
  "B378": "University Place",
  "B379": "Coney Island Creek Park",
  "B380": "Robert E. Venable Park",
  "B381": "Thomas Boyland Park",
  "B383": "Success Garden",
  "B384": "Fresh Creek Nature Preserve",
  "B385": "WNYC Transmitter Park",
  "B386": "Ten Eyck Plaza",
  "B387": "Hilltop Playground",
  "B388": "Gateway Triangle",
  "B389": "Umma Park",
  "B390": "Mother Cabrini Park",
  "B391": "Lt. Federico Narvaez Tot Lot",
  "B392": "Lott Park",
  "B393": "Sheepshead Bay Piers",
  "B394": "Four Sparrow Marsh",
  "B395": "Green Central Knoll",
  "B396": "Nehemiah Park",
  "B397": "Carter G. Woodson Children's Park",
  "B400": "Hattie Carthan Community Garden",
  "B401": "Grand Ferry Park",
  "B402": "George Walker Jr. Park",
  "B403": "Harmony Park",
  "B404": "East Flatbush Children's Playground",
  "B405": "Epiphany Playground",
  "B406": "Paerdegat Basin Park",
  "B407": "South Oxford Park",
  "B418": "Valentino Pier",
  "B419": "Sutter Ballfields",
  "B429": "Hope Ballfield",
  "B430": "Lewis Playground",
  "B431": "Brooklyn Bridge Park",
  "B432": "American Veterans Memorial Pier",
  "B433": "Hendrick I. Lott House",
  "B434": "Old Gravesend Cemetery",
  "B529": "Bushwick Inlet Park",
  "B536": "North 5th Street Pier and Park",
  "B541": "Berriman Playground",
  "B555": "Beaver Noll Park",
  "B585": "Prospect Plaza Park",
  "B588": "Greenpoint Public Park",
  "B591": "Schaefer Landing",
  "B592": "Betty Carter Park",
  "B594": "Maple Street Community Garden",
  "B595": "Greenpoint Landing",
  "B596": "Flatbush African Burial Ground",
  "B597": "Kingsborough Houses Bergen Playground",
  "B599": "Kingsborough Houses Pacific Playground",
  "B603": "Jerzee Triangle",
  "B605": "Ascenzi Square",
  "B606": "Fowler Square",
  "M001": "Abingdon Square",
  "M002": "Ahearn Park",
  "M003": "Annunciation Playground",
  "M004": "Allen Street Malls",
  "M005": "The Battery",
  "M006": "Tribeca Park",
  "M007": "Bowling Green",
  "M008": "Bryant Park",
  "M009": "Bennett Park",
  "M010": "Central Park",
  "M011": "Chelsea Park",
  "M012": "Christopher Park",
  "M013": "City Hall Park",
  "M014": "Jackie Robinson Park",
  "M015": "Columbus Park",
  "M016": "Cooper Triangle",
  "M017": "Corlears Hook Park",
  "M018": "Carmansville Playground",
  "M019": "Coleman Playground",
  "M020": "Dante Park",
  "M021": "A Philip Randolph Square",
  "M022": "De Witt Clinton Park",
  "M023": "Donnellan Square",
  "M024": "Dorrance Brooks Square",
  "M025": "Duane Park",
  "M026": "Dyckman House Museum",
  "M027": "Downing Street Playground",
  "M028": "Fort Washington Park",
  "M029": "Fort Tryon Park",
  "M030": "Thomas Paine Park",
  "M031": "Amelia Gorman Park",
  "M032": "Greeley Square Park",
  "M033": "Hamilton Fish Park",
  "M034": "Hancock Park",
  "M035": "Brigadier General Charles Young Triangle",
  "M036": "Herald Square",
  "M037": "Highbridge Park",
  "M038": "James J Walker Park",
  "M039": "Harlem River Park",
  "M040": "Johnny Hartman Square",
  "M041": "Alexander Hamilton Playground",
  "M042": "Inwood Hill Park",
  "M043": "Isham Park",
  "M044": "Jackson Square",
  "M045": "John Jay Park",
  "M046": "Vietnam Veterans Plaza",
  "M047": "Thomas Jefferson Park",
  "M048": "Joan Of Arc Park",
  "M051": "Richard Tucker Park",
  "M052": "Madison Square Park",
  "M053": "Theodore Roosevelt Park",
  "M054": "Mitchel Square",
  "M055": "Montefiore Square",
  "M056": "Morningside Park",
  "M058": "Marcus Garvey Park",
  "M059": "Murphy Brothers Playground",
  "M061": "Plaza Lafayette",
  "M063": "Gertrude Ederle Recreation Center",
  "M064": "Lillian D Wald Playground",
  "M065": "Luther Gulick Park",
  "M066": "Dr. Gertrude B. Kelly Playground",
  "M067": "Sophie Irene Loeb",
  "M069": "Vesuvio Playground",
  "M070": "Queensboro Oval",
  "M071": "Riverside Park",
  "M073": "Roger Morris Park",
  "M076": "St. Vartan Park",
  "M077": "St. Nicholas Park",
  "M079": "St. Catherine's Park",
  "M080": "Schiff Mall",
  "M081": "Carl Schurz Park",
  "M082": "Seward Park",
  "M083": "Sherman Square",
  "M085": "Straus Park",
  "M086": "Stuyvesant Square",
  "M087": "Sakura Park",
  "M088": "Tompkins Square Park",
  "M089": "Union Square Park",
  "M090": "Lafayette Square",
  "M091": "Bennett Rest",
  "M093": "Father Duffy Square",
  "M094": "Broadway Malls",
  "M096": "Adam Clayton Powell Jr. Malls",
  "M097": "Verdi Square",
  "M098": "Washington Square Park",
  "M099": "J. Hood Wright Park",
  "M101": "Worth Square",
  "M103": "Tony Dapolito Recreation Center",
  "M104": "Randall's Island Park",
  "M105": "Sara D. Roosevelt Park",
  "M107": "Wards Island Park",
  "M110": "William McCray Playground",
  "M111": "James Weldon Johnson Playground",
  "M113": "Joseph C. Sauer Park",
  "M116": "ABC Playground",
  "M122": "Captain Jacob Joseph Playground",
  "M123": "Peretz Square",
  "M124": "First Park",
  "M127": "Bushman Steps",
  "M130": "Constance Baker Motley Recreation Center",
  "M131": "Hansborough Recreation Center",
  "M132": "Little Flower Playground",
  "M138": "Bill Bojangles Robinson Playground",
  "M140": "Recreational Area",
  "M141": "Percy E. Sutton Playground",
  "M144": "John V. Lindsay East River Park",
  "M145": "Albert Capsouto Park",
  "M148": "White Playground",
  "M154": "Mathews-Palmer Playground",
  "M155": "Courtney Callender Playground",
  "M156": "McKenna Square",
  "M158": "Robert Moses Playground",
  "M159": "Frederick Johnson Playground",
  "M160": "Fred Samuel Playground",
  "M161": "McCaffrey Playground",
  "M164": "Asser Levy Playground",
  "M165": "Baruch Playground",
  "M166": "Harlem Art Park",
  "M167": "Peck Slip",
  "M169": "Samuel Marx Triangle",
  "M170": "Petrosino Square",
  "M171": "Cherry Clinton Playground",
  "M172": "McCarthy Square",
  "M177": "Honey Locust Park",
  "M178": "Catherine Slip Malls",
  "M180": "Lt. Wm. Tighe Triangle",
  "M182": "Vladeck Park",
  "M183": "Peter Minuit Playground",
  "M184": "Samuel N. Bennerson 2nd Playground",
  "M186": "Brigadier General Charles Young Playground",
  "M187": "Marx Brothers Playground",
  "M188": "Abe Lebewohl Park",
  "M189": "Roosevelt Triangle",
  "M190": "Sheltering Arms Playground",
  "M191": "Father Demo Square",
  "M192": "Stanley Isaacs Playground",
  "M193": "Abraham Lincoln Playground",
  "M194": "Alfred E. Smith Playground",
  "M195": "Sidney Hillman Playground",
  "M196": "Playground One",
  "M198": "Martin Luther King, Jr. Playground",
  "M199": "Monsignor Kett Playground",
  "M200": "Booker T. Washington Playground",
  "M201": "Wald Playground",
  "M204": "Moore Playground",
  "M205": "Playground One Twenty Five CXXV",
  "M206": "Tanahey Playground",
  "M207": "Father Fagan Park",
  "M209": "Mill Rock Park",
  "M212": "The Queen Elizabeth II September 11th Garden",
  "M213": "Mae Grant Playground",
  "M214": "Blake Hobbs Playground",
  "M215": "Cherry Tree Park",
  "M216": "Holcombe Rucker Park",
  "M217": "Howard Bennett Playground",
  "M218": "DeSalvio Playground",
  "M219": "Tecumseh Playground",
  "M220": "Frederick Douglass Playground",
  "M221": "Gutenberg Playground",
  "M222": "Grand Canal Court",
  "M223": "Jacob H. Schiff Playground",
  "M224": "Straus Square",
  "M225": "Wagner Playground",
  "M226": "Augustus St. Gaudens Playground",
  "M227": "Peter's Field",
  "M228": "Henry M. Jackson Playground",
  "M229": "Happy Warrior Playground",
  "M230": "Poor Richard's Playground",
  "M231": "Damrosch Park",
  "M232": "Lincoln Center Plaza",
  "M233": "Matthew P. Sapolin Playground",
  "M234": "Wright Brothers Playground",
  "M235": "Sol Lain Plgd",
  "M236": "Samuel Seabury Playground",
  "M237": "Corporal John A. Seravalli Playground",
  "M238": "Bloomingdale Playground",
  "M239": "P.S. 155 Playground",
  "M240": "Audubon Playground",
  "M241": "Nathan Straus Playground",
  "M242": "Collect Pond Park",
  "M243": "Eugene McCabe Field",
  "M244": "Sol Bloom Playground",
  "M245": "Renaissance Playground",
  "M246": "Kimlau Square",
  "M247": "St. James Triangle",
  "M249": "Penn South Playground",
  "M251": "Bleecker Playground",
  "M254": "Gustave Hartman Square",
  "M255": "James Madison Plaza",
  "M256": "MacArthur Playground",
  "M257": "Clement Clarke Moore Park",
  "M258": "East River Playground",
  "M259": "McKinley Playground",
  "M260": "Chelsea Recreation Center",
  "M263": "Bellevue South Park",
  "M264": "Playground Eighty Nine LXXXIX",
  "M265": "Vincent F. Albano Jr. Playground",
  "M270": "Dry Dock Playground",
  "M273": "Wagner Houses Pool",
  "M276": "The Public Theater",
  "M277": "Hell's Kitchen Park",
  "M279": "Duarte Square",
  "M280": "Tramway Plaza",
  "M282": "Septuagesimo UNO",
  "M283": "Battery Park City",
  "M284": "Convent Garden",
  "M285": "Dr. Ronald E. McNair Playground",
  "M286": "Asphalt Green",
  "M287": "Sheridan Square Viewing Garden",
  "M288": "Ramon Aponte Park",
  "M289": "East River Esplanade",
  "M290": "Pier 107 CVII",
  "M292": "Sunshine Playground",
  "M294": "Ruppert Park",
  "M295": "Mercer Playground",
  "M300": "Sherman Creek",
  "M301": "St. Gregory's Playground",
  "M302": "Detective Omar Edwards Park",
  "M303": "Abyssinian Tot Lot",
  "M304": "West 186th Street Basketball Court",
  "M308": "Washington Market Park",
  "M318": "Merchant's House Museum",
  "M321": "Lower East Side Playground",
  "M353": "Riverside Park South",
  "M355": "Robert L. Clinkscales Playground and Community Garden",
  "M360": "The High Line",
  "M366": "Tribeca Dog Run",
  "M369": "Pier 42",
  "M376": "West Harlem Piers",
  "M378": "Pearl St Playground",
  "M379": "Canal Park",
  "M385": "DeLury Square",
  "M386": "Imagination Playground",
  "M391": "East River Waterfront Esplanade",
  "M395": "Fiorello La Guardia Park",
  "M399": "Bella Abzug Park",
  "M402": "Chelsea Green",
  "M404": "NYC AIDS Memorial Park at St. Vincent’s Triangle",
  "M411": "Plaza",
  "M413": "Rapkin-Gayle Plaza",
  "M414": "Manuel Plaza",
  "M415": "Lorraine Hansberry Plaza",
  "Q001": "Alley Pond Park",
  "Q002": "Grover Cleveland Playground",
  "Q003": "Ashmead Park",
  "Q004": "Astoria Park",
  "Q005": "Baisley Pond Park",
  "Q006": "Bowne Park",
  "Q007": "Bayswater Park",
  "Q008": "Brookville Park",
  "Q009": "Hermon A. MacNeil Park",
  "Q010": "Clearview Park Golf Course",
  "Q011": "Poppenhusen Playground",
  "Q012": "Crocheron Park",
  "Q013": "Veterans Grove",
  "Q014": "Astoria Heights Playground",
  "Q015": "Forest Park",
  "Q017": "The Olde Towne of Flushing Burial Ground",
  "Q018": "Gordon Triangle",
  "Q019": "Garlinge Triangle",
  "Q021": "Cunningham Park",
  "Q022": "Margaret I. Carman Green - Weeping Beech",
  "Q023": "Rufus King Park",
  "Q024": "Kissena Park",
  "Q025": "Major Mark Park",
  "Q026": "Park Of The Americas",
  "Q027": "Laurelton Parkway",
  "Q028": "Beach Channel Park",
  "Q029": "William F Moore Park",
  "Q030": "Midland Malls",
  "Q031": "Lawrence Virgilio Playground",
  "Q032": "McKenna Triangle",
  "Q033": "Mall Eighteen",
  "Q034": "Sabba Park",
  "Q035": "Mall Thirty Four XXXIV",
  "Q037": "Neponsit Mall",
  "Q038": "Benninger Playground",
  "Q040": "Elmjack Mall",
  "Q041": "Newtown Playground",
  "Q042": "Poppenhusen Park",
  "Q043": "Proctor-Hopson Circle",
  "Q044": "L/CPL Thomas P. Noonan Jr. Playground",
  "Q045": "Andrews Grove",
  "Q046": "Josephine Caminiti Playground",
  "Q047": "Queens Village Veterans Plaza",
  "Q048": "Rainey Park",
  "Q050": "Rockaway Beach",
  "Q051": "Archie Spigner Park",
  "Q052": "Captain Tilly Park",
  "Q053": "Equity Playground",
  "Q055": "Veteran's Square",
  "Q056": "Clemens Triangle",
  "Q057": "Sohncke Square",
  "Q058": "Dunningham Triangle",
  "Q059": "Catharine Turner Richardson Park",
  "Q060": "Nine Heroes Plaza",
  "Q061": "Steinmann Triangle",
  "Q062": "Fleetwood Triangle",
  "Q063": "Luke J. Lang Square",
  "Q065": "John Vincent Daniels Jr. Square",
  "Q067": "Pigeon Paradise",
  "Q069": "Middleburgh Triangle",
  "Q070": "Trolley Car Triangle",
  "Q072": "Short Triangle",
  "Q073": "Plaut Triangle",
  "Q075": "Glendale Veterans Triangle",
  "Q076": "Legion Triangle",
  "Q079": "Wellbrock Triangle",
  "Q080": "Veterans Plaza",
  "Q082": "Wayanda Park",
  "Q083": "Jackie Robinson Parkway",
  "Q084": "Grand Central Parkway",
  "Q085": "Gorman Playground",
  "Q086": "Flushing Fields",
  "Q090": "Federalist Triangle",
  "Q092": "Police Officer Edward Byrne Park",
  "Q094": "Tudor Park",
  "Q095": "Vito Locascio Field",
  "Q096": "Belt Parkway",
  "Q098": "Frank D. O'Connor Playground",
  "Q099": "Flushing Meadows Corona Park",
  "Q100": "Flushing Greens",
  "Q101": "Middle Village Playground",
  "Q102": "Juniper Valley Park",
  "Q103": "Raymond O’Connor Park",
  "Q104": "Queensbridge Park",
  "Q105": "Howard Von Dohlen Playground",
  "Q106": "Daniel M. O'Connell Playground",
  "Q107": "Springfield Park",
  "Q108": "Laurelton Playground",
  "Q116": "One Room Schoolhouse Park",
  "Q118": "Police Officer Nicholas Demutiis Park",
  "Q119": "Frederick B. Judge Playground",
  "Q120": "Harvard Playground",
  "Q121": "Detective Keith L Williams Park",
  "Q122": "Junction Playground",
  "Q123": "Astoria Health Playground",
  "Q124": "Myrtle Avenue Clemens Triangle",
  "Q126": "Francis Lewis Park",
  "Q127": "Marconi Park",
  "Q128": "London Planetree Playground",
  "Q129": "Phil \"Scooter\" Rizzuto Park",
  "Q130": "Motor Parkway",
  "Q131": "Frank Principe Park",
  "Q133": "Pat Williams Playground",
  "Q134": "Jack Breininger Park",
  "Q135": "Cross Island Parkway",
  "Q136": "Playground 115",
  "Q137": "Columbus Square",
  "Q139": "Drumm Triangle",
  "Q140": "Barclay Triangle",
  "Q141": "Murray Playground",
  "Q142": "Jacob Riis Triangle",
  "Q147": "Ruoff Triangle",
  "Q148": "Catholic War Veterans Square",
  "Q151": "Grand Slope",
  "Q152": "Horsebrook Island",
  "Q157": "Metro Triangle",
  "Q159": "Father Reilly Square",
  "Q160": "O'Sullivan Plaza",
  "Q162": "Rockaway Beach and Boardwalk",
  "Q163": "Rockaway Beach Boardwalk",
  "Q165": "Spring Creek Park Addition",
  "Q168": "Alexander Grey Triangle",
  "Q172": "Corona Plaza",
  "Q173": "American Triangle",
  "Q177": "Tudor Malls",
  "Q178": "Mall Forty Two XLII",
  "Q186": "Jackson Mill Green",
  "Q190": "Corporal Ruoff Square",
  "Q203": "David J O'Connell Square",
  "Q206": "Eight Oaks Triangle",
  "Q207": "MacDonald Park",
  "Q208": "Litchhult Square",
  "Q209": "Lawrence Triangle",
  "Q211": "Maple Playground",
  "Q212": "Queens Valley Playground",
  "Q213": "Studley Triangle",
  "Q214": "Leonard Square",
  "Q215": "Whitey Ford Field",
  "Q217": "Lt. Frank McConnell Park",
  "Q218": "Dutch Kills Playground",
  "Q219": "Rockaway Freeway",
  "Q221": "Farm Playground",
  "Q222": "Glenwood Landing",
  "Q223": "Fresh Meadows Park",
  "Q224": "Calvary Monument",
  "Q225": "Broad Channel Veteran's Park",
  "Q226": "Hallets Cove Playground",
  "Q231": "Sergeant Colyer Square",
  "Q232": "Dwyer Square",
  "Q243": "Norelli-Hargreaves Memorial Triangle",
  "Q245": "Hollis Veterans Square",
  "Q246": "Travis Triangle",
  "Q254": "Corporal Frank F. Fagan Sq.",
  "Q257": "Lt. Clinton L .Whiting Square",
  "Q259": "Memorial Circle",
  "Q262": "Alameda Malls",
  "Q266": "Westbourne Playground",
  "Q267": "Court Square Park",
  "Q268": "Bell Malls",
  "Q275": "Patricia A. Brackley Park",
  "Q277": "South Gate Mall",
  "Q281": "Nakks Malls",
  "Q283": "225 Street Malls",
  "Q284": "Sixteen Oaks Grove",
  "Q285": "Al Stabile Playground",
  "Q289": "Pinocchio Playground",
  "Q290": "\"Uncle\" Vito F. Maranzano Glendale Playground",
  "Q291": "Starr Playground",
  "Q293": "Saul Weprin Playground",
  "Q294": "Utopia Playground",
  "Q296": "Playground Thirty Five XXXV",
  "Q298": "Paul Raimonda Playground",
  "Q299": "Overlook Park",
  "Q300": "Kissena Corridor Park",
  "Q301": "Jamaica Playground",
  "Q302": "Evergreen Park",
  "Q303": "Travers Park",
  "Q304": "Ehrenreich-Austin Playground",
  "Q305": "Mafera Park",
  "Q306": "The Painter's Playground",
  "Q307": "Delphin H. Greene Playground",
  "Q308": "Bowne Playground",
  "Q309": "Jamaica Bay Park",
  "Q310": "Glen Oaks Oval",
  "Q313": "Arverne Playground",
  "Q314": "Fresh Meadows Playground",
  "Q316": "Captain Dermody Triangle",
  "Q317": "Tall Oak Playground",
  "Q318": "Playground Eighty LXXX",
  "Q319": "Annadale Playground",
  "Q320": "Vleigh Playground",
  "Q321": "Van Alst Playground",
  "Q322": "Bellaire Playground",
  "Q325": "Gladys Warren Triangle",
  "Q326": "James A. Bland Playground",
  "Q327": "Castlewood Playground",
  "Q328": "Bellerose Playground",
  "Q329": "Pomonok Playground",
  "Q330": "Locust Manor Playground",
  "Q332": "Woodtree Playground",
  "Q333": "Ravenswood Playground",
  "Q334": "Playground Twenty One",
  "Q335": "Russell Sage Playground",
  "Q336": "Judge Moses Weinstein Playground",
  "Q337": "Maurice A FitzGerald Playground",
  "Q338": "Admiral Playground",
  "Q339": "Cambria Playground",
  "Q340": "Torsney Playground",
  "Q342": "Electric Playground",
  "Q343": "Whitestone Playground",
  "Q344": "Emerald Playground",
  "Q345": "Redfern Playground",
  "Q346": "Challenge Playground",
  "Q347": "Colden Playground",
  "Q348": "Willow Lake Playground",
  "Q349": "Telephone Playground",
  "Q351": "Peters Field",
  "Q352": "Hillside Playground",
  "Q353": "Grassmere Playground",
  "Q354": "Playground Seventy Five",
  "Q355": "Strippoli Square",
  "Q356": "Alley Park",
  "Q358": "Detective William T. Gunn Playground",
  "Q359": "Haggerty Park",
  "Q361": "Moore Homestead Playground",
  "Q362": "Playground Ninety",
  "Q363": "Northern Playground",
  "Q364": "Marie Curie Playground",
  "Q366": "Louis C. Moser Playground",
  "Q367": "Hammel Playground",
  "Q369": "Louis Pasteur Park",
  "Q370": "Freedom Square Playground",
  "Q371": "Rockaway Community Park",
  "Q373": "Helen Marshall Playground",
  "Q375": "Willets Point Playground",
  "Q376": "Cedar Grove Playground",
  "Q377": "Playground Sixty Two LXII",
  "Q378": "Ampere Playground",
  "Q379": "Briarwood Playground",
  "Q381": "Francis Lewis Playground",
  "Q382": "Cardozo Playground",
  "Q383": "Middle Village Veterans Triangle",
  "Q385": "Ditmars Playground",
  "Q386": "Centreville Playground",
  "Q388": "Linnaeus Park",
  "Q389": "Bayside Playground",
  "Q390": "Clintonville Playground",
  "Q391": "Joseph Austin Playground",
  "Q392": "Idlewild Park",
  "Q394": "Conch Playground",
  "Q395": "Steinway Playground",
  "Q396": "Montbellier Park",
  "Q397": "Auburndale Playground",
  "Q398": "Rosemary's Playground",
  "Q399": "Bay Terrace Playground",
  "Q400": "Oakland Gardens",
  "Q401": "Lost Battalion Hall Recreation Center",
  "Q402": "Latimer Playground",
  "Q403": "Beach Channel Playground",
  "Q404": "East Springfield Playground",
  "Q405": "Hollis Playground",
  "Q406": "Springfield Park North",
  "Q407": "Lanett Playground",
  "Q408": "Harold Schneiderman Playground",
  "Q410": "Hinton Park",
  "Q411": "Douglaston Park Golf Course",
  "Q412": "Gwen Ifill Park",
  "Q413": "Rochdale Park",
  "Q414": "Rocket Playground",
  "Q415": "Louis Armstrong Playground",
  "Q419": "Hart Playground",
  "Q421": "Walter Ward Playground",
  "Q422": "Seaside Playground",
  "Q423": "Reiff Playground",
  "Q424": "Judge Angelo Graci Triangle",
  "Q425": "Yellowstone Park",
  "Q426": "North Rochdale Playground",
  "Q427": "South Rochdale Playground",
  "Q428": "Horace Harding Playground",
  "Q429": "Spirit Playground",
  "Q430": "Sunrise Playground",
  "Q434": "Long Island Mews",
  "Q435": "Vernon Mall",
  "Q436": "Athens Square",
  "Q437": "Murray Hill Playground",
  "Q439": "Private William Gray Playground",
  "Q440": "Hilton Holiday Gardens",
  "Q441": "Fisher Pool",
  "Q443": "Almeda Playground",
  "Q444": "Sean's Place",
  "Q445": "Frank Golden Park",
  "Q446": "Sorrentino Recreation Center",
  "Q447": "Brinkerhoff Mall",
  "Q448": "Roy Wilkins Recreation Center",
  "Q450": "Corona Golf Playground",
  "Q451": "Underbridge Dog Run",
  "Q452": "Udall's Park Preserve",
  "Q453": "Queens Farm Park",
  "Q454": "Hook Creek Park",
  "Q456": "Gene Gray Playground",
  "Q457": "College Point Park",
  "Q458": "Fort Totten Park",
  "Q459": "Dubos Point Wildlife Sanctuary",
  "Q460": "Broad Channel Park",
  "Q461": "Powell's Cove Park",
  "Q462": "Manuel De Dios Unanue Triangle",
  "Q463": "Cornell Burial Ground",
  "Q464": "Brant Point Wildlife Sanctuary",
  "Q465": "Socrates Sculpture Park",
  "Q467": "Broad Channel American Park",
  "Q468": "Louis Armstrong Community Center",
  "Q469": "Seagirt Ave Wetlands",
  "Q470": "A.R.R.O.W. Field House",
  "Q471": "Hunter's Point South Park",
  "Q472": "Vernam Barbadoes Peninsula",
  "Q474": "Simeone Park",
  "Q476": "College Point Fields",
  "Q478": "Broad Channel Wetlands",
  "Q480": "Remsen Family Cemetery",
  "Q481": "Southside Burial Ground",
  "Q482": "Prospect Cemetery",
  "Q483": "Corona Health Sanctuary",
  "Q491": "Carlos R. Lillo Park",
  "Q492": "Elmhurst Park",
  "Q494": "Flight 587 Memorial Park",
  "Q496": "Park at Beach 108 Street",
  "Q497": "Lewis H Latimer House",
  "Q498": "Sunset Cove Park",
  "Q499": "Bay Breeze Park",
  "Q501": "Sergeant Collins Triangle",
  "Q502": "Rory Staunton Field",
  "Q506": "Gateway Park",
  "Q509": "Nameoke Park",
  "Q510": "Maspeth Park",
  "Q514": "Woodside Houses Park",
  "Q515": "Legacy Park",
  "Q516": "Lt. Michael R. Davidson Playground",
  "Q517": "Brinckerhoff Cemetery",
  "Q520": "Arverne East Nature Preserve",
  "R002": "Pleasant Plains Plaza",
  "R003": "Barrett Park",
  "R004": "Barrett Triangle",
  "R005": "Clove Lakes Park",
  "R006": "Conference House Park",
  "R008": "Faber Pool and Park",
  "R009": "Amundsen Circle",
  "R010": "Staats Circle",
  "R011": "Hero Park",
  "R012": "John E. White Park",
  "R013": "LaTourette Park & Golf Course",
  "R015": "Walker Park",
  "R016": "Great Kills Park",
  "R017": "Freshkills Park",
  "R019": "Veterans Park",
  "R020": "Egbert Triangle",
  "R021": "Forest Mall",
  "R022": "Silver Lake Park",
  "R024": "Tompkinsville Park",
  "R025": "Mahoney Playground",
  "R026": "Gerard P. Dugan Playground",
  "R027": "Long Pond Park",
  "R028": "Tappen Park",
  "R029": "Westerleigh Park",
  "R030": "Willowbrook Park",
  "R031": "Wolfe's Pond Park",
  "R032": "Maple Woods",
  "R033": "Levy Playground",
  "R034": "Austin J. McDonald Playground",
  "R035": "De Matti Park",
  "R036": "Bobbie Lewis Jr. Playground",
  "R037": "Liotti Ikefugi Playground",
  "R038": "Midland Playground",
  "R042": "Kaltenmeier Playground",
  "R043": "Lyons Pool",
  "R045": "Schmul Park",
  "R046": "Franklin D. Roosevelt Boardwalk and Beach",
  "R047": "Willowbrook Parkway",
  "R048": "Jones Woods Park",
  "R050": "Forest Grove",
  "R052": "Allison Pond Park",
  "R053": "Harris Brothers Park",
  "R057": "Haven Esplanade Park",
  "R059": "Von Briesen Park",
  "R060": "Dodgers Triangle",
  "R061": "Rev. Dr. Maggie Howard Playground",
  "R062": "Arrochar Playground",
  "R063": "Old Town Playground",
  "R064": "Christopher J. Igneri Playground",
  "R065": "Richmond Parkway",
  "R066": "North Shore Esplanade",
  "R067": "Gen. Douglas MacArthur Park",
  "R068": "The Big Park",
  "R069": "Terrace Playground",
  "R070": "Clove's Tail",
  "R071": "Great Kills Veterans Playground",
  "R072": "Clawson Playground",
  "R073": "Naples Playground",
  "R076": "Markham Playground",
  "R077": "St. George Park",
  "R078": "Northerleigh Park",
  "R079": "Lemon Creek Park",
  "R080": "Annadale Green",
  "R085": "E.M.T. Christopher J. Prescott Playground",
  "R086": "Davis Playground",
  "R087": "Dongan Playground",
  "R088": "High Rock Park",
  "R089": "Greencroft Playground",
  "R090": "Lieutenant John H. Martinson Playground",
  "R097": "Ida Court",
  "R100": "Drumgoole Tot Lot",
  "R101": "Wegener Park",
  "R104": "South Shore Country Club",
  "R105": "Prall Playground",
  "R106": "Bloomingdale Park",
  "R107": "New Dorp Park",
  "R109": "CPL. Thompson Park",
  "R110": "Tottenville Pool",
  "R111": "Lt. Lia Playground",
  "R112": "Meredith Woods",
  "R114": "Jennifer's Playground",
  "R115": "Deere Park",
  "R116": "Snug Harbor Cultural Center",
  "R117": "Alice Austen Park",
  "R118": "Reed's Basket Willow Swamp Park",
  "R119": "Blue Heron Park",
  "R120": "Arden Woods",
  "R121": "Siedenburg Park",
  "R122": "Pralls Island",
  "R123": "Cottages Hill New Brighton Park",
  "R124": "Eibs Pond Park",
  "R125": "Lopez Playground",
  "R126": "Gaeta Park",
  "R127": "Joseph Manna Park",
  "R128": "Shooters Island",
  "R129": "Blood Root Valley",
  "R130": "Saw Mill Creek Marsh",
  "R131": "Huguenot Ponds Park",
  "R132": "Bunker Ponds Park",
  "R133": "Arbutus Woods Park",
  "R135": "Crescent Beach Park",
  "R136": "Hybrid Oak Woods Park",
  "R137": "Bayview Terrace Park",
  "R138": "Kingdom Pond Park",
  "R139": "Tottenville Shore Park",
  "R140": "King Fisher Park",
  "R141": "Graniteville Swamp Park",
  "R143": "Staten Island Industrial Park",
  "R144": "Sobel Court Park",
  "R145": "Seaside Wildlife Nature Park",
  "R147": "South Beach Wetlands",
  "R148": "Last Chance Pond Park",
  "R149": "Ocean Breeze Park",
  "R150": "Graniteville Quarry Park",
  "R151": "Isle Of Meadows",
  "R152": "Carlton Park",
  "R153": "Fairview Park",
  "R154": "Richmond Terrace Cemetery",
  "R155": "South Clove Road Cemetery",
  "R156": "Sylvan Grove Cemetery",
  "R157": "Sleight Family Graveyard",
  "R158": "Fort Hill Park",
  "R159": "Old Place Creek Park",
  "R160": "Heritage Park",
  "R161": "Laredo Avenue Parcel",
  "R162": "Olmsted-Beil House Park",
  "R164": "Targee Street Triangle",
  "R165": "Blueberry Park",
  "R166": "Manor Park",
  "R167": "Richmond Terrace Park",
  "R169": "Goodhue Park",
  "R170": "Stapleton Esplanade",
  "R172": "Brookfield Park",
  "R173": "Snug Harbor Cemetery",
  "X001": "Aqueduct Walk",
  "X002": "Bronx Park",
  "X003": "Pelham Parkway",
  "X004": "Bronx River Parkway",
  "X005": "Bryan Park",
  "X006": "Bergen Triangle",
  "X007": "Castle Hill Park",
  "X008": "Claremont Park",
  "X009": "Monsignor Raul Del Valle Square",
  "X010": "Crotona Park",
  "X011": "Crotona Parkway Malls",
  "X012": "Church Triangle",
  "X013": "Devoe Park",
  "X014": "Horseshoe Playground",
  "X015": "Joseph Rodman Drake Park & Enslaved African Burial Ground",
  "X016": "Owen F. Dolen Park",
  "X017": "Richman (Echo) Park",
  "X018": "Echo Triangle",
  "X019": "Ewen Park",
  "X020": "Fort Independence Playground",
  "X021": "Drew Playground",
  "X022": "Benjamin Gladstone Square",
  "X023": "Graham Triangle",
  "X025": "Hugh J. Grant Circle",
  "X026": "Hines Park",
  "X028": "Joyce Kilmer Park",
  "X029": "Lyons Square Playground",
  "X030": "Macombs Dam Park",
  "X031": "McKinley Square",
  "X032": "Railroad Park",
  "X033": "Mosholu Parkway",
  "X034": "Rev. T. Wendell Foster Park and Recreation Center",
  "X035": "Muller Triangle",
  "X036": "Murphy Triangle",
  "X037": "O'Brien Oval",
  "X038": "Washington's Walk",
  "X039": "Pelham Bay Park",
  "X040": "Poe Park",
  "X041": "Pulaski Park",
  "X042": "Rose Hill Park",
  "X043": "Ryan Triangle",
  "X044": "St. James Park",
  "X045": "St. Mary's Park",
  "X046": "Seton Falls Park",
  "X047": "Franz Sigel Park",
  "X049": "Schneider Sampson Square",
  "X051": "University Woods",
  "X053": "O'Neill Triangle",
  "X055": "Brust Park",
  "X057": "Michel Triangle",
  "X058": "Keltch Park",
  "X059": "Sergeant Johnson Triangle",
  "X060": "Sheridan Triangle",
  "X061": "Flood Triangle",
  "X062": "Beatty Plaza",
  "X063": "Martin Luther King Triangle",
  "X064": "Bryant Triangle",
  "X065": "Woodrow Wilson Triangle",
  "X068": "D'Auria-Murphy Triangle",
  "X069": "Hutton Triangle",
  "X070": "Heath Triangle",
  "X071": "Whalen Grove",
  "X073": "Young Park",
  "X077": "Featherbed Triangle",
  "X078": "Franklin Triangle",
  "X079": "Major General John R Brown Triangle",
  "X080": "Henry Hudson Park",
  "X081": "Mount Eden Malls",
  "X082": "University Malls",
  "X084": "D'Onofrio Square",
  "X085": "Slattery Playground",
  "X086": "Charlton-Thompson Garden",
  "X087": "Zimmerman Playground",
  "X088": "Pugsley Creek Park",
  "X090": "Spuyten Duyvil Shorefront Park",
  "X092": "Van Cortlandt Park",
  "X093": "Van Nest Park",
  "X094": "Bridge Park",
  "X095": "Marcus Garvey Square",
  "X096": "Rita Ley Triangle",
  "X101": "Hutchinson River Parkway",
  "X102": "Ciccarone Park",
  "X103": "People's Park",
  "X104": "Williamsbridge Oval",
  "X105": "Jerome Slope",
  "X106": "Evelina Antonetty Playground",
  "X107": "Hawkins Park",
  "X110": "Henry Hudson Parkway",
  "X111": "Cedar Playground",
  "X112": "Hilton White Playground",
  "X113": "Hunts Point Playground",
  "X114": "Goble Playground",
  "X115": "Mott Playground",
  "X116": "Rev J Polite Playground",
  "X118": "Soundview Park",
  "X119": "Alexander's Alley",
  "X121": "Bufano Park",
  "X122": "Colucci Playground",
  "X123": "Noble Playground",
  "X124": "Watson Gleason Playground",
  "X126": "Ferry Point Park",
  "X129": "Devanney Triangle",
  "X130": "Barry Plaza",
  "X131": "Lozada Playground",
  "X133": "Derosa O'Boyle Triangle",
  "X134": "Freeman Triangle",
  "X136": "Harris Park",
  "X137": "Jerome Park",
  "X138": "Playground One Thirty Four CXXXIV",
  "X139": "Gouverneur Morris Triangle",
  "X141": "Rienzi Playground",
  "X142": "Riverdale Park",
  "X146": "Flynn Playground",
  "X149": "Miele Park",
  "X151": "P.O. Serrano Playground",
  "X152": "Vinmont Veteran Park",
  "X153": "Merriam Playground",
  "X154": "Melrose Playground",
  "X155": "Patterson Playground",
  "X156": "Eastchester Playground",
  "X157": "Mazzei Playground",
  "X158": "Sedgwick Playground",
  "X159": "Captain William Harry Thompson Playground",
  "X160": "Caserta Playground",
  "X161": "Gun Hill Playground",
  "X162": "Parkside Playground",
  "X163": "Loreto Playground",
  "X164": "Dawson Playground",
  "X165": "Edenwald Playground",
  "X166": "Behagen Playground",
  "X168": "Nelson Playground",
  "X169": "Agnes Haywood Playground",
  "X170": "The Pearly Gates",
  "X171": "Spuyten Duyvil Playground",
  "X172": "Allerton Playground",
  "X174": "Webster Playground",
  "X175": "Riverbend Playground",
  "X176": "Taylor Playground",
  "X177": "Castle Hill Playground",
  "X178": "Matthews Muliner Playground",
  "X179": "Al Quiñones Playground",
  "X180": "Whalen Playground",
  "X182": "Millbrook Playground",
  "X183": "Bruckner Playground",
  "X185": "Dunbar Playground",
  "X186": "Riverdale Playground",
  "X187": "Givan Square",
  "X188": "Wakefield Playground",
  "X190": "Tiffany Playground",
  "X193": "Stars & Stripes Playground",
  "X194": "Captain Rivera Playground",
  "X196": "Haffen Park",
  "X197": "Mosholu Playground",
  "X200": "Clark Playground",
  "X201": "Seton Park",
  "X202": "Marble Hill Playground",
  "X203": "Randall Playground",
  "X204": "Story Playground",
  "X205": "FDNY-EMT Yadira Arroyo Playground",
  "X206": "Morgan Playground",
  "X207": "Pontiac Playground",
  "X208": "Haviland Playground",
  "X209": "Wave Hill",
  "X211": "Stebbins Playground",
  "X214": "Magenta Playground",
  "X215": "Valentine Varian House",
  "X216": "Abigail Playground",
  "X217": "Willis Playground",
  "X219": "Arcilla Playground",
  "X221": "Space Time Playground",
  "X222": "Gouverneur Playground",
  "X224": "MacLaughlin Playground",
  "X228": "I-Am-Park",
  "X232": "Burns Playground",
  "X233": "Fountain Of Youth Playground",
  "X235": "Grove Hill Playground",
  "X236": "Mapes Pool",
  "X238": "Saw Mill Playground",
  "X239": "Castle Hill Little League Field",
  "X242": "Youth Village",
  "X243": "Estella Diggs Park",
  "X244": "Grand Playground",
  "X246": "Brook Park",
  "X247": "Fox Park",
  "X248": "Barretto Park",
  "X250": "Kingsbridge Heights Community Center",
  "X251": "Co-op City Field",
  "X252": "Bathgate Playground",
  "X253": "Ambrosini Field",
  "X255": "Bill Rainey Park",
  "X256": "Pelham Bay Little League",
  "X257": "Mount Hope Playground",
  "X258": "Cleopatra Playground",
  "X259": "Raoul Wallenberg Forest",
  "X260": "Julio Carballo Fields",
  "X261": "Kwame Ture Recreation Center",
  "X262": "Harding Park",
  "X263": "Quarry Ballfields",
  "X264": "Field Of Dreams Court",
  "X265": "Galileo Playground",
  "X266": "Vidalia Park",
  "X267": "Eae J Mitchell Park",
  "X268": "Givans Creek Woods",
  "X269": "Cpl Fischer Park",
  "X271": "Grant Park",
  "X272": "Ranaqua Playground",
  "X273": "Rock Garden Park",
  "X274": "Mount Hope Garden",
  "X278": "Boston Garden",
  "X279": "City Island Wetlands",
  "X281": "Stop & Go Playground",
  "X282": "Seabury Playground",
  "X283": "Beanstalk Playground",
  "X284": "Printers Park",
  "X286": "Rev Lena Irons Unity Park",
  "X287": "Ogden Plimpton Playground",
  "X288": "West Farms Rapids",
  "X289": "Mapes Park",
  "X290": "Longfellow Playground",
  "X291": "Walton Park",
  "X292": "Mabel Hampton Playground",
  "X294": "Palmer Inlet",
  "X295": "Half-Nelson Playground",
  "X299": "Little Claremont Playground",
  "X300": "Davidson Playground",
  "X302": "Thorpe Family Playground",
  "X304": "Tiffany Street Pier",
  "X305": "Concrete Plant Park",
  "X306": "Garrison Park",
  "X307": "Barretto Point Park",
  "X308": "North Brother Island",
  "X309": "South Brother Island",
  "X310": "Locust Point Marina",
  "X311": "West Farms Soldiers Cemetery",
  "X312": "Ferris Family Burial Plot",
  "X334": "Mohegan Triangle",
  "X335": "Risse Street Park",
  "X336": "Hunts Point Riverside Park",
  "X344": "Mill Pond Park",
  "X348": "River Avenue Parks",
  "X350": "Melrose Commons Park",
  "X353": "Yolanda García Park",
  "X354": "P.S. 29 Ballfield",
  "X362": "Catherine Scott Promenade",
  "X367": "Dr. Thomasina Bushby Park",
  "X369": "Watson Houses Playground",
  "X370": "Hart Island",
  "X373": "Justice Sotomayor Houses Playground",
};

export const BOROUGH_LABELS: Record<string, string> = {
  M: "Manhattan",
  B: "Brooklyn",
  Q: "Queens",
  X: "Bronx",
  R: "Staten Island",
};

export function getBoroughFromId(parkId: string): string {
  return BOROUGH_LABELS[parkId[0]] ?? "Unknown";
}